import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { PropsWithChildren } from 'react'
import Navbar from './navbar'
import '../globals.css'
import { cn } from '@/lib/utils'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }: PropsWithChildren) {
	return (
		<html lang='en'>
			<body className={cn('text-gray-800', inter.className)}>
				<Navbar />
				<main>{children}</main>
			</body>
		</html>
	)
}
